### ISSUE TITLE
Customer unsubscribe push

### ISSUE THREAD

**Issue by mmojadad** [aldabil21/opencart-webpush-pwa#1]
Hi
What will be solution for Customer unsubscribe push?

Regards

**Comment by aldabil21** [comment]
Hi @mmojadad 

Customer can unsubscribe, the toggle button will show customer if he already is subscribed or not.
You can find the toggle functions here:
https://github.com/aldabil21/opencart-webpush-pwa/blob/2be216ac76eb414567c981427abadd4d1aadeade/catalog/view/theme/default/template/common/home.twig#L51

Also the serverworker functions here: https://github.com/aldabil21/opencart-webpush-pwa/blob/2be216ac76eb414567c981427abadd4d1aadeade/catalog/view/javascript/serviceworker.js
